### ISSUE TITLE
Any way to use this outside android

### ISSUE THREAD

**Issue by Niksac** [selpic-handy-printer/wifilib#1]
We got one of your printers but we need to feed the input from a program of ours.
Any way to get example code outside of the android world?

**Comment by ipcjs** [comment]
This library also has an iOS version, but it has not yet been published to github.  You can contact our sales person and ask him to give you the library for iOS.

**Comment by Niksac** [comment]
We would like to run this on linux / windows.
The reliance on `import com.wzygswbxm.wifilib` prevent us from doing this at the moment.
Are those parts open source too?

**Comment by ipcjs** [comment]
This part is currently not open source.

What error is reported when running the code, can you send the log?

**Comment by ipcjs** [comment]
Can you build the `sample`?

**Comment by ipcjs** [comment]
This part is currently not open source. but we have provide a aar.

What error is reported when running the code, can you provide error log?

Can you build the `sample`?
The sample use jetpack compose, so it required  Android studio 4.0.0-alpha08.

**Comment by ipcjs** [comment]
If your issue is resolved, please close the issue.
